notifications:
    email: false

sudo: required

services:
    - docker

before_install:
    # Create .splunkrc file with default credentials
    - echo host=localhost >> $HOME/.splunkrc
    - echo username=admin >> $HOME/.splunkrc
    - echo password=changed! >> $HOME/.splunkrc
    # Set env vars for TCP/UDP tests (we've punched these through Docker)
    - export TEST_TCP_PORT=10667
    - export TEST_UDP_PORT=10668
    # Set SPLUNK_HOME
    - export SPLUNK_HOME="/opt/splunk"
    # Add DOCKER to iptables, 1/10 times this is needed, force 0 exit status
    - sudo iptables -N DOCKER || true
    # Start docker-compose in detached mode
    - docker-compose up -d
    # Health Check (3 minutes)
    - for i in `seq 0 180`; do if docker exec -it splunk /sbin/checkstate.sh &> /dev/null; then break; fi; echo $i; sleep 1; done


language: java

env:
  - SPLUNK_VERSION=7.3
  - SPLUNK_VERSION=8.0

addons:
  apt:
    packages:
      - ant-optional

jdk:
  - openjdk8

before_script:
    - ant

script: ant travis
